#! /bin/bash

lol_version=$(curl --silent https://ddragon.leagueoflegends.com/realms/euw.json | jq -r .v)
if [[ -z $lol_version ]]
then
	$lol_version=13.1.1
fi

if [[ -z $LOL_MOTD_REGION ]]
then
	LOL_MOTD_REGION=euw1
fi

if [[ -z $LOL_MOTD_SUMMONER ]]
then
	echo "Need summoner id \$LOL_MOTD_SUMMONER"
	exit 1
fi

if [[ -z $RIOT_KEY ]]
then
	echo "Need riot api key \$RIOT_KEY"
	exit 1
fi

if [[ -z $LOL_MOTD_CHAMP ]]
then
	echo "Need champion name \$LOL_MOTD_CHAMP"
	exit 1
fi

champ_id=$(curl --silent "https://ddragon.leagueoflegends.com/cdn/$lol_version/data/en_US/champion/$LOL_MOTD_CHAMP.json" | jq -r .data.$LOL_MOTD_CHAMP.key)

if [[ -z $champ_id ]]
then
	echo "no champ named $LOL_MOTD_CHAMP :("
	exit 1
fi

echo "Champ id $champ_id"

score=$(curl --silent "https://euw1.api.riotgames.com/lol/champion-mastery/v4/champion-masteries/by-summoner/$LOL_MOTD_SUMMONER/by-champion/$champ_id" -H "X-Riot-Token: $RIOT_KEY" | jq .championPoints)

if [[ $score -eq null ]]
then
	echo "Failed to get score :("
	exit 1
fi

echo "Score: $score"

if [[ $score -ge 1000 ]]
then
	
	if [[ $score -le 100000 ]]
	then
		score=$(bc <<< "scale=2; $score/1000")
	elif [[ $score -le 1000000 ]]
	then
		score=$(bc <<< "$score/1000")K
	else
		score=$(bc <<< "scale=2; $score/1000000")M
	fi

fi

echo "Update motd"
figlet "$LOL_MOTD_CHAMP $score" > /etc/motd.d/10-header
